Models/FreeBirdModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OzLearningHub.Models
{
    public class FreeBirdModel
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public string Color { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OzLearningHub.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult SignIn()
        {
            return View();

        }
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Account()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OzLearningHub.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult NewStuff(int? id)
        //public ActionResult NewStuff(int? id) - this can be used as well
        //public ActionResult NewStuff(int id=0) - this is having 0 as default in case if we do not pass any other value

        {

            ViewBag.qty = id;
            return View();
        }

        //public ActionResult AddNumber(string num1, string num2)
        //{
        //    ViewBag.a = num1;
        //    ViewBag.b = num2;

        //    return View();
        //}


        public ActionResult AddNumber(FormCollection form)
        {
            double num1, num2; 

            var num1Success = Double.TryParse(form["num1"], out num1);
            var num2Success = Double.TryParse(form["num2"], out num2);

            if (num1Success && num2Success)
            {
                ViewBag.Total = num1 + num2;

                ViewBag.a = num1;
                ViewBag.b = num2;
            }


            ViewBag.a = form["num1"];
            ViewBag.b = form["num2"];
            
            //ViewBag.Total = ViewBag.a + ViewBag.b + ViewBag.c;

            return View();
        }


        public ActionResult DisplayList()

        {

            ViewBag.Names = new string[] {"Jim", "Joe", "Janice", "Joan"};

            

            return View();
        }


    }
}

Controllers/LessonsController.cs
using OzLearningHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace OzLearningHub.Controllers
{
    public class LessonsController : Controller
    {
        // GET: Lessons
        public ActionResult Homework1()
        {
            return View();
        }

        public ActionResult Lesson1_2()
        {
            return View();
        }

        //FreeBird Assignment: Lesson 7-9
        public ActionResult Lesson7_9(string name = "Unknown", int age = -1, string color = "N/A")
        {
            var model = new FreeBirdModel()
            {
                Name = name,
                Age = age,
                Color = color,
            };

            return View(model);
        }

        public ActionResult Lesson9_10()
        {
            return View();
        }


        //Here is where the color mixer will happen
        public ActionResult Homework2(string colorMix1, string colorMix2)
        {
            if (colorMix1 == "1" && colorMix2 =="1")
            {
                ViewBag.mixedColor = "Red";
            }
            else if ((colorMix1 == "1" && colorMix2 == "3") || (colorMix1 == "3" && colorMix2 == "1"))
            {
                ViewBag.mixedColor = "Yellow";

            }
            else if ((colorMix1 == "1" && colorMix2 == "2") || (colorMix1 == "2" && colorMix2 == "1"))
            {
                ViewBag.mixedColor = "Magenta";
            }
            else if (colorMix1 == "3" && colorMix2 == "3")
            {
                ViewBag.mixedColor = "Green";
            }
            else if (colorMix1 == "2" && colorMix2 == "2")
            {
                ViewBag.mixedColor = "Blue";
            }
            else if ((colorMix1 == "3" && colorMix2 == "2") || (colorMix1 == "2" && colorMix2 == "3"))
            {
                ViewBag.mixedColor = "Cyan";
            }

            List<SelectListItem> colors = new List<SelectListItem>();
            SelectListItem color1 = new SelectListItem() {Text = "Red", Value = "1", Selected = false};
            SelectListItem color2 = new SelectListItem() { Text = "Blue", Value = "2", Selected = false};
            SelectListItem color3 = new SelectListItem() { Text = "Green", Value = "3", Selected = false };

            colors.Add(color1);
            colors.Add(color2);
            colors.Add(color3);
            //passing this value to Html Dropdown on backend side
            ViewBag.colorMix = colors;
            

            return View();
        }

        public ActionResult Lesson12()
        {
            // create an array of strings

            // "put" the array in the ViewBag
            ViewBag.balloons = balloons;

            return View();
        }
        //creating new method birthday

        string[] balloons = { "Red", "Blue", "Green", "Purple" };

        [HttpPost]
        public ActionResult Lesson12(FormCollection form)
        {

            @ViewBag.ResultName = form["name"];
            @ViewBag.ResultDB = form["birthday"];

            var balloon = form.AllKeys
                .Where(k => k.StartsWith("balloon"))
                .Select(k => form[k]);


            //foreach (var balloon in balloons)
            //{
            //    var b = form[balloon].Split(',');       //true, falsae
            //    var val = b[0];
            //    bool isChecked = Convert.ToBoolean(val);


            //    if (isChecked)      // if balloon checkbox is true
            //    {
            //        balloonList.Add(balloon); //add name of the balloon
            //    }
            //}

            ViewBag.BalloonList = balloon;  // storing values of checked balloons

            return View("Results");
        }


        public bool IsThisAKeyWeNeed(string x)
        {
            if (x.StartsWith("balloon"))

                return true;
            return false;
        }



    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OzLearningHub.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Category()
        {
            return View();
        }

        public ActionResult Discount()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/AddNumber.cshtml
@{
    ViewBag.Title = "AddNumbers";

}

<h3>num1: @ViewBag.a</h3>
<h3>num2: @ViewBag.b</h3>
@*<h3>num3: @ViewBag.c</h3>*@

<h2> Total: @ViewBag.Total</h2>


<form role="form" style="padding-left: 10px;" method="post" action="@Url.Action("AddNumber","Home")">
    <div class="form-group">
        @Html.Label("num1", "First number")
        @*<label for="num1">First number</label>    **** same as line above *@
        @Html.TextBox("num1", null, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("num2", "Second number")
        @* <label for="num2">Second number</label>   **** same as line above*@
        @Html.TextBox("num2", null, new { @class = "form-control" })
        @*<input type="text" class="form-control" id="num2" name="num2"> **** same as line above*@
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/DisplayList.cshtml
@{
    ViewBag.Title = "DisplayList";
}

<h2>DisplayList</h2>

<h3>List of Names</h3>

<ul>
    @{

        foreach (var Names in ViewBag.Names)
        {
            <li>@Names </li>
        }

    }

</ul>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="container" id="jumbo">
    <div class="jumbotron">
        <!--Used the following: https://css3gen.com/text-shadow/ -->
        <h1 style="text-shadow: 4px 4px 2px rgba(150, 150, 150, 1);">N<i class="far fa-compass" style="font-size:45px"></i>rthwind</h1>
        <p>
            Best price and high quality guaranteed!<br />
            Check out our featured discounts below!
        </p>
        <button class="btn btn-primary">Place Your Order >></button>
    </div>

    <!--Grid System-->
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-3">
                <h3>Tis the Seasoning</h3>
                <hr />
                <p>Order today to save 25% on Chef Anton's Italian seassoning. You don't want to make Chef's mad, do you? </p>
                <br />
                <p><i>Discount Expires: 12/12/2018</i></p>
                <a href="#" class="fas fa-hand-point-right"> Discount Code</a>
            </div>

            <div class="col-md-4 col-md-3 col-sm-3 ">
                <h3>Go Green</h3>
                <hr />
                <p>Get 15% off your next purchase when you Opt Out from you monthly statements!</p>
                <br />
                <p><i>Discount Expires: 12/12/2018</i></p>
                <a href="#" class="fas fa-hand-point-right"> Discount Code</a>
            </div>

            <div class="col-md-4 col-md-3 col-sm-3">
                <h3>Half Price </h3>
                <hr />
                <p>This month only! Our special iteam will be 50% off. Do not miss it!</p>
                <br />
                <p><i>Discount Expires: 12/12/2018</i></p>
                <a href="#" class="fas fa-hand-point-right"> Discount Code</a>
            </div>
        </div>
    </div>
</div>

<!--<nav class="navbar navbar-inverse navbar-fixed-bottom na">
    <div class="container">
        <p class="navbar-text">MVC<span class="glyphicon glyphicon-apple"></span></p>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-area">Sing In</button>


        <button type="button" class="btn btn-danger">Sing Up</button>
        <button type="button" class="btn arrow">TEST!</button>
    </div>
</nav>-->

Views/Home/NewStuff.cshtml
@{
    ViewBag.Title = "NewStuff";

    double price = 1.5;
    int qty = ViewBag.qty;

    double total = price * qty;
}

<div class="panel panel-info">
    <div class ="panel-heading"><h3>Order Details</h3></div>
    <div class="panel-body">
        <h3>QTY: @qty</h3>
        <h3>Price: @price.ToString("C")</h3>
        <h3>Total: @total.ToString("C")</h3>

    </div>
</div>

Views/Lessons/Homework1.cshtml
@{
    ViewBag.Title = "Homework1";
}

<!--Fun fonts-->


<div class="container" id="jumbo">
    <div class="jumbotron">
        <!--Used the following: https://css3gen.com/text-shadow/ -->
        <h1 style="text-shadow: 4px 4px 2px rgba(150, 150, 150, 1);">N<i class="far fa-compass" style="font-size:45px"></i>rthwind</h1>
        <p>
            Best price and high quality guaranteed!<br />
            Check out our featured discounts below!
        </p>
        <a href="https://google.com" class="btn btn-primary" target={_blank}>Place Your Order >></a>
    </div>

    <!--Grid System-->
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-3">
                <h3>Tis the Seasoning</h3>
                <hr />
                <p>Order today to save 25% on Chef Anton's Italian seassoning. You don't want to make Chef's mad, do you? </p>
                <br />
                <p><i>Discount Expires: 12/12/2018</i></p>
                <a href="#" class="fas fa-hand-point-right"> Discount Code</a>
            </div>

            <div class="col-md-4 col-md-3 col-sm-3 ">
                <h3>Go Green</h3>
                <hr />
                <p>Get 15% off your next purchase when you Opt Out from you monthly statements!</p>
                <br />
                <p><i>Discount Expires: 12/12/2018</i></p>
                <a href="#" class="fas fa-hand-point-right"> Discount Code</a>
            </div>

            <div class="col-md-4 col-md-3 col-sm-3">
                <h3>Half Price </h3>
                <hr />
                <p>This month only! Our special iteam will be 50% off. Do not miss it!</p>
                <br />
                <p><i>Discount Expires: 12/12/2018</i></p>
                <a href="#" class="fas fa-hand-point-right"> Discount Code</a>
            </div>
        </div>
    </div>
</div>

<!--<nav class="navbar navbar-inverse navbar-fixed-bottom na">
    <div class="container">
        <p class="navbar-text">MVC<span class="glyphicon glyphicon-apple"></span></p>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-area">Sing In</button>


        <button type="button" class="btn btn-danger">Sing Up</button>
        <button type="button" class="btn arrow">TEST!</button>
    </div>
</nav>-->

Views/Lessons/Homework2.cshtml
@{
    ViewBag.Title = "ColorMixer";
    

}

<h2 style="font: bold; color: slateblue">Color Mixer</h2>

<form role="form" style="padding-left: 10px;" method="post" action="@Url.Action("Homework2","Lessons")">
    <div class="form-group">
        <h3 style="padding-left: 5px;">Pick You First Color</h3>
        @Html.DropDownList("colorMix1", (IEnumerable<SelectListItem>)ViewBag.colorMix, " (none) ", new { id = "colorPick", @class = "form-control", @style = "margin-left: 10px" })
    </div>

    <div class="form-group">
        <h3 style="padding-left: 5px;">Pick You Second Color</h3>
        @Html.DropDownList("colorMix2", (IEnumerable<SelectListItem>)ViewBag.colorMix, " (none) ", new { id = "colorPick", @class = "form-control", @style = "margin-left: 10px" })
    </div>
    <br>

    <button type="submit" class="btn btn-default">Submit</button>

    @* Need to write a loop to pick the color  *@
    <h3 style="padding-left: 5px; color: @ViewBag.mixedColor">
        Your Mixed Color is: @ViewBag.mixedColor

    </h3>

</form>

Views/Lessons/Lesson12.cshtml
@{
    ViewBag.Title = "Birthday";
}

<link href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- content -->
<div class="container" style="min-width:480px;">
    <h1>Happy Birthday!</h1>
    <hr />
    <form role="form" action="" method="post">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.Label("name", "Name")
                    @Html.TextBox("name", null, new { placeholder = "Enter name", required = "required", @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.Label("birthday", "Birthday")
                    @Html.TextBox("birthday", null, new { placeholder = "Enter birthday", required = "required", @class = "form-control", id = "datepicker" })
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Select your favorite balloons</strong></h3>
                    </div>
                    <div class="panel-body">
                        @{
                            foreach (var balloon in ViewBag.balloons)
                            {
                                String ball = Convert.ToString(balloon);
                                string balloonKey = "balloon" + ball;

                                <div class="checkbox" style="padding-left: 20px;">

                                    <input type="checkbox" id="@ball" name="@balloonKey" value="@ball" class="bx" />
                                    @*@Html.CheckBox(ball, false, new {@class = "bx"})*@
                                    @Html.Label(ball, ball + " balloons")
                                </div>
                            }
                        }
                        <button type="button" id="clear_add" value="check all">Check All / Uncheck All</button>
                    </div>
                </div>
                <button type="submit" class="btn btn-default" onclick="href='~/Lessons/Results.cshtml'" >Submit</button>
            </div>
            <div class="col-sm-6" style="text-align:center;">
                @{
                    foreach (var balloon in ViewBag.balloons)
                    {
                        string imagename = "../Images/" + balloon + ".png";
                        string id = balloon + "Img";
                        <img src="@imagename" alt="@balloon" class="ball" id="@id" />
                    }
                }
            </div>
        </div>
    </form>
</div>





<script type="text/javascript">
    $(function () {
        $('#datepicker').datepicker();
    });

    $(function () {
        $('.ball').draggable();

    });

    $('.bx').change(function () {
        $('#' + $(this).attr('id') + 'Img').css('visibility', 'visible')
        $(this).is(':checked') ?
            $('#' + $(this).attr('id') + 'Img').removeClass().addClass('animated bounceInDown') :
            $('#' + $(this).attr('id') + 'Img').addClass('animated bounceOutUp')
    });

    $('.bx').each(function () {
        $(this).is(':checked') ?
            $('#' + $(this).attr('id') + 'Img').css('visibility', 'visible') : //true
            $('#' + $(this).attr('id') + 'Img').css('visibility', 'hidden') //false: if this will be written- baloons will be hidden and next functions below will not work
    });

    $('.bx').change(function () {
        $('#' + $(this).attr('id') + 'Img').css('visibility', 'visible')
        $(this).is(':checked') ?
            $('#' + $(this).attr('id') + 'Img').removeClass().addClass('animated bounceInDown') :
            $('#' + $(this).attr('id') + 'Img').addClass('animated bounceOutUp')
    });


    
    $("#clear_add").on('click', function () {
        $("input.bx").click();

    });

    $('.ball').click(function () {
        $('input.bx').click();   

    });

    // attach datepicker to textbox
    //$('#birthday').datepicker({ dateFormat: "mm-dd" });



</script>

Views/Lessons/Lesson1_2.cshtml
@{
    ViewBag.Title = "Lesson1_2";
}

<link href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


<div class="container">
    <h1 class="animated bounce">Happy Birthday!</h1>

    <form role="form">
        <div class="row">
            <!--Data Entry-->
            <div class="col-sm-6">
                <div class="form-group animated bounce">
                    <label for="name">Name</label>
                    <input type="text" id="name" class="form-control" />
                </div>



                <div class="form-group">
                    <label for="name">Date</label>
                    <input type="text" id="datepicker" class="form-control" />
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <strong>Select YourFavorite Baloon</strong>
                        </h3>
                    </div>

                    <div class="checkbox">
                        <label><input type="checkbox" class="bx" id="rb" />red</label>
                    </div>
                    <div class="checkbox">
                        <label> <input type="checkbox" class="bx" id="gb" />blue</label>
                    </div>
                    <div class="checkbox">
                        <label> <input type="checkbox" class="bx" id="bb" />green</label>
                    </div>
                </div>
                <button type="button" class="btn btn-default">Submit</button>
            </div>

            <div class="col-sm-6">
                <img src="~/Images/red.png" alt="red" class="ball" id="rbImg" />
                <img src="~/Images/blue.png" alt="blue" class="ball" id="bbImg" />
                <img src="~/Images/blue_green.png" alt="green" class="ball" id="gbImg" />
            </div>
        </div>
    </form>

</div>


<div class="navbar-fixed-bottom">
    <span class="copy">&copy; Copyright 2018 OZ</span>
</div>


<script type="text/javascript">
    $(function () {
        $('#datepicker').datepicker();
    });

    $(function () {
        $('.ball').draggable();

    });

    $('.bx').change(function () {
        $('#' + $(this).attr('id') + 'Img').css('visibility', 'visible')
        $(this).is(':checked') ?
            $('#' + $(this).attr('id') + 'Img').removeClass().addClass('animated bounceInDown') :
            $('#' + $(this).attr('id') + 'Img').addClass('animated bounceOutUp')
    });

    $('.bx').each(function () {
        $(this).is(':checked') ?
            $('#' + $(this).attr('id') + 'Img').css('visibility', 'visible') : //true
            $('#' + $(this).attr('id') + 'Img').css('visibility', 'hidden') //false: if this will be written- baloons will be hidden and next functions below will not work
    });

    $('.bx').change(function () {
        $('#' + $(this).attr('id') + 'Img').css('visibility', 'visible')
        $(this).is(':checked') ?
            $('#' + $(this).attr('id') + 'Img').removeClass().addClass('animated bounceInDown') :
            $('#' + $(this).attr('id') + 'Img').addClass('animated bounceOutUp')
    });

</script>

Views/Lessons/Lesson7_9.cshtml
@model OzLearningHub.Models.FreeBirdModel

@{
    ViewBag.Title = "Bird";
}

<h2 style="margin-left: 10px;">Assignment for Lessons 7-9: Free Bird</h2>

<div style="margin-left: 10px;">
    <p>Name: @Model.Name</p>
    <p>Age: @Model.Age</p>
    <p>Color: @Model.Color</p>
</div>

Views/Lessons/Lesson9_10.cshtml
@{
    ViewBag.Title = "AddNumbers";

}

<h3>num1: @ViewBag.a</h3>
<h3>num2: @ViewBag.b</h3>
@*<h3>num3: @ViewBag.c</h3>*@

<h2> Total: @ViewBag.Total</h2>


<form role="form" style="padding-left: 10px;" method="post" action="@Url.Action("AddNumber","Home")">
    <div class="form-group">
        @Html.Label("num1", "First number")
        @*<label for="num1">First number</label>    **** same as line above *@
        @Html.TextBox("num1", null, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("num2", "Second number")
        @* <label for="num2">Second number</label>   **** same as line above*@
        @Html.TextBox("num2", null, new { @class = "form-control" })
        @*<input type="text" class="form-control" id="num2" name="num2"> **** same as line above*@
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

Views/Lessons/Results.cshtml
@{
    ViewBag.Title = "Results";
}



<style>
    h1 {
        text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,.1), 0 0 5px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.3), 0 3px 5px rgba(0,0,0,.2), 0 5px 10px rgba(0,0,0,.25), 0 10px 10px rgba(0,0,0,.2), 0 20px 20px rgba(0,0,0,.15);
    }
</style>

<h1 style="color: cornflowerblue">HAPPY BIRTHDAY</h1>


<h2 style="font-style: italic">Thank you @ViewBag.ResultName</h2>


<div style="padding-left: 10px">
    <h3> Your birthday is on @ViewBag.ResultDB, And...</h3>

    <h3>You have selected the folowing balloons:</h3>
    <ul>
        @{
            foreach (var balloon in ViewBag.BalloonList)
            {
                <li style="font-size: 20px; color:@balloon">@balloon</li>
            }
        }
    </ul>
</div>

Views/Products/Category.cshtml
@{
    ViewBag.Title = "Category";

    var x = 1;
    var y = x + 1;

}

<h2>Category: @y</h2>

Views/Products/Discount.cshtml
@{
    ViewBag.Title = "Discount";
}

<h2>Discount</h2>

Views/Products/Products.cshtml
@{
    ViewBag.Title = "Prodcuts";
}

<h2>Products</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="Northwind" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Application</title>

    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/animate.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">

    <link href="~/css/MyStyles.css" type="text/css" rel="stylesheet" />

  
    <!--Fun fonts-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">




    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>

<body>
    <!--Navbar-->
    <!--Navigation Bar-->
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" id="navbar">

        <!--HomeBtnOnTheHeader-->
        <a href="#" class="navbar-brand" style="font-family:'Gloria Hallelujah', cursive;">Northwind</a>
        <!--HamburgerMenu-->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-menu">
                    <!--Reference to the id for the collapse bar-->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @* @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

            </div>
            <!--Links on the Header-->
            <div class="collapse navbar-collapse topnav-left" id="collapse-menu">

                <!--Bellow will makes links to collapse with window resize-->
                <ul class="nav navbar-nav navbar-left">
                    <!--DropDown: it requires JQuery script-->
                    <li>
                        <a class="dropdown-toggle fas fa-book" data-toggle="dropdown" href="#"> Products<b class="caret"></b></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="https://getbootstrap.com/docs/3.3/css/">Browse Categories</a></li>
                            <li><a href="@Url.Action("Category", "Products")">Product Search</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("Discount", "Products")">Current Discounts</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle fas fa-user" data-toggle="dropdown" href="#"> Customers<b class="caret"></b></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="@Url.Action("SignIn", "Customer")">Sign In</a></li>
                            <li><a href="@Url.Action("Register","Customer")">Register</a></li>
                            <li class="divider"></li>
                            <li><a href="@Url.Action("Account","Customer")">Your Account</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle fas fa-chalkboard" data-toggle="dropdown" href="#"> My Lesson<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Homework 1", "Homework1", "Lessons")</li>
                            <li>@Html.ActionLink("Homework 2", "Homework2", "Lessons")</li>
                            <li>@Html.ActionLink("Lesson 1-2", "Lesson1_2", "Lessons")</li>
                            <li>@Html.ActionLink("Lesson 7-9", "Lesson7_9", "Lessons")</li>
                            <li>@Html.ActionLink("Lesson 9-10", "Lesson9_10", "Lessons")</li>
                            <li>@Html.ActionLink("Lesson 12", "Lesson12","Lessons")</li>
                        </ul>
                    </li>

                    <!--ProductSearch searchBox-->

                    <li class="form-group hidden-xs">
                        <input type="text" class="form-control" data-toggle="collapse" data-target="bs-navbar-collapse" placeholder="Product Search">
                    </li>

                    <!--Search Button-->
                    <li><button type="button" class="btn btn-default navbar-btn hidden-xs">Search</button></li>
                </ul>
                <ul class="nav navbar-nav navbar-right glyphicon1">
                    <!--Sign Out-->
                    <!-- <li class="glyphicon glyphicon-log-out" style="color:mintcream; padding-top:16px; padding-left:7px"></li>-->
                    <li class="SignOutBtn"><a href="#" class="fas fa-sign-out-alt">Sign Out</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()

    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@



    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @RenderSection("scripts", required: false)
</body>
</html>